<div class="hero-unit">
<h3>Mobile Dungeon</h3>
We are building up a mobile Dungeon, 
submit to our beta programm. 

<form action="/" method="POST">
<input type="text" name="email" /><br />
<input type="submit" value="i am interested" /><br />

</form>

Ot tweet us @MobileDungeon

</div>
<h4 >News </h4>
<a href="https://twitter.com/share" class="twitter-share-button" data-via="MobileDungeon" data-lang="de" data-hashtags="sw">Twittern</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>